# Generated by Django 4.2.6 on 2023-10-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineApp', '0009_participation_reservationstand_remove_jour_edition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
