# Generated by Django 4.2.6 on 2023-10-19 11:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineApp', '0010_evenement_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('title', models.TextField(blank=True, default='', null=True)),
                ('subtitle', models.TextField(blank=True, default='', null=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, default='images/blogs/default.png', max_length=255, null=True, upload_to='images/blogs/')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
