# Generated by Django 4.2.6 on 2023-10-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineApp', '0012_participation_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='client_secret',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='payement_intent',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='price',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='participation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
