# Generated by Django 4.2.6 on 2023-12-06 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vitrineApp', '0015_alter_participation_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('fullname', models.TextField(blank=True, default='', null=True)),
                ('contact', models.TextField(blank=True, default='', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('objet', models.TextField(default='')),
                ('message', models.TextField(default='')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
