# Generated by Django 4.2.6 on 2023-10-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqueApp', '0004_produit_recette_faqproduit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqproduit',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='recette',
        ),
        migrations.AddField(
            model_name='faqproduit',
            name='question',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='faqproduit',
            name='reponse',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_commande', to='boutiqueApp.client'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
