# Generated by Django 4.2.6 on 2023-10-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqueApp', '0005_remove_faqproduit_faq_remove_produit_categorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='code',
            new_name='avis',
        ),
        migrations.AddField(
            model_name='produit',
            name='faq',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='infos',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='recettes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
