# Generated by Django 4.2.6 on 2023-11-03 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boutiqueApp', '0006_rename_code_produit_avis_produit_faq_produit_infos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='price',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_commande', to=settings.AUTH_USER_MODEL),
        ),
    ]
