# Generated by Django 4.2.6 on 2023-11-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqueApp', '0007_commande_price_alter_commande_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
