# Generated by Django 4.2.6 on 2023-11-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqueApp', '0008_alter_commande_price_alter_lignecommande_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client_secret',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='quantite',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
