# Generated by Django 4.2.6 on 2023-12-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqueApp', '0010_alter_lignecommande_commande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='state',
        ),
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
