# Generated by Django 4.2.6 on 2023-12-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutiqueApp', '0011_remove_commande_state_commande_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='price_reduction',
            field=models.IntegerField(default=0),
        ),
    ]
